disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 #- force_try
 #- function_parameter_count
 - force_cast
 - multiple_closures_with_trailing_closure # Conflicts with Xcode closures auto completions

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - TDDCourseTests
 - TDDCourseUITests

line_length: 250

force_cast: warning # implicitly
force_try:
    severity: warning # explicitly

file_length:
  warning: 500
  error: 750
  
type_body_length:
  - 500 # warning
  - 700 # error

function_body_length: 70

identifier_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50

type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 12
