name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check Swift Coherency
      uses: arthurpalves/coherent-swift@0.5.5
      with:
        source: Sources/
        minimum_threshold: 60
        ignore_output_result: true
        only_changes: false
        report_format: plain
