name: Features Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  swiftlint:
    name: Swift Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install SwiftLint
        run: mint install realm/SwiftLint

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          swiftlint: true

  build-and-test:
    needs: swiftlint
    
    name: Build & Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: set -o pipefail 

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app

    - name: Build and test
      run: xcodebuild clean build test -project TDDCourse.xcodeproj -scheme "TDDCourse" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
      #run: xcodebuild clean build test -workspace App/QuizApp.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
