name: Swift Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action for SwiftLint with --strict
      uses: norio-nomura/action-swiftlint@3.1.0
      with:
        args: --strict
